film/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *


urlpatterns = patterns(
    '',
    url(r'^search/$', search_films_json,  name='json-films'),

    # Dropbox
    url(r'^(?P<pk>\d+)/upload/dropbox/$', upload_from_dropbox,  name='upload-from-dropbox'),
    url(r'^(?P<pk>\d+)/upload/dropbox/progress/$', dropbox_upload_progress, name='dropbox-upload-progress'),
    url(r'^(?P<pk>\d+)/upload/dropbox/cancel/$', cancel_dropbox_upload,  name='cancel-dropbox-upload'),

    # Add and edit
    url(r'^add/$', add_film, name='add-film'),
    url(r'^add/(?P<pk>\d+)/media/$', add_film_media, name='add-film-media'),
    url(r'^add/(?P<pk>\d+)/festivals/$', add_film_festivals, name='add-film-festivals'),
    url(r'^add/(?P<pk>\d+)/reviews/$', add_film_reviews, name='add-film-reviews'),
    url(r'^add/(?P<pk>\d+)/cast/$', add_film_cast, name='add-film-cast'),
    url(r'^add/(?P<pk>\d+)/logistics/$', add_film_logistics, name='add-film-logistics'),
    # url(r'^imdb_info/$', get_imdb_info, name='imdb-info'),
    url(r'^(?P<pk>\d+)/edit/$', edit_film, name='edit-film'),
    url(r'^(?P<pk>\d+)/delete/$', delete_film, name='delete-film'),

    # Festivals
    url(r'^add/festivals/add-film/$', add_film_on_festival, name='add-film-on-festival'),
    # url(r'^festival/ajax/create/$', add_festival, name='add-festival'),
    # url(r'^festivals/(?P<pk>\d+)/$', festival_details,  name='festival-details'),
    # url(r'^festivals/delete/$', delete_fof,  name='delete-fof'),
    # url(r'^festivals/$', list_festivals, name='list-festivals'),

    # Stills
    url(r'^(?P<pk>\d+)/stills/upload/$', upload_still_image, name='upload-film-still'),
    url(r'^stills/remove/$', remove_still, name='remove-still'),

    # Files
    url(r'^(?P<pk>\d+)/files/exhibition/$', upload_exhibition_file, name='upload-exhibition-file'),
    url(r'^(?P<pk>\d+)/files/exhibition/download/$', download_exhibition_file, name='download-exhibition-file'),
    url(r'^(?P<pk>\d+)/files/exhibition/ftp-download/$', download_exhibition_file_ftp, name='download-exhibition-file-ftp'),
    url(r'^(?P<pk>\d+)/files/exhibition/dropbox-download/$', download_exhibition_file_dropbox, name='download-exhibition-file-dropbox'),
    url(r'^(?P<pk>\d+)/files/exhibition/ftp_upload_info/$', ftp_upload_info, name='ftp-upload-info'),
    url(r'^users_dropbox_files/$', users_dropbox_files, name='users-dropbox-files'),

    # Reviews
    url(r'^(?P<film_id>\d+)/reviews/add/$', add_review, name='add-review'),
    url(r'^reviews/delete/$', delete_review, name='delete-review'),

    # Cast & Crew
    url(r'^(?P<film_pk>\d+)/cast/add/$', add_cast, name='add-cast'),
    url(r'^(?P<film_pk>\d+)/crew/add/$', add_crew, name='add-crew'),
    url(r'^(?P<film_pk>\d+)/cast/(?P<cast_pk>\d+)/delete/$', delete_cast,  name='delete-cast'),
    url(r'^(?P<film_pk>\d+)/crew/(?P<crew_pk>\d+)/delete/$', delete_crew,  name='delete-crew'),

    # PreviewRequest
    url(r'^(?P<pk>\d+)/preview_request/$', send_preview_request, name='send-preview-request'),
    url(r'^(?P<film_id>\d+)/preview_request/(?P<prev_req_id>\d+)/accept/$', accept_preview_request, name='film-accept-preview-request'),
    url(r'^(?P<film_id>\d+)/preview_request/(?P<prev_req_id>\d+)/decline/$', decline_preview_request, name='film-decline-preview-request'),

    # DownloadRequest
    url(r'^(?P<pk>\d+)/download_request/$', send_download_request, name='send-download-request'),
    url(r'^(?P<film_id>\d+)/download_request/(?P<down_req_id>\d+)/accept/$', accept_download_request, name='film-accept-download-request'),
    url(r'^(?P<film_id>\d+)/download_request/(?P<down_req_id>\d+)/decline/$', decline_download_request, name='film-decline-download-request'),

    # Film payment
    url(r'^(?P<pk>\d+)/payment/$', film_payment, name='film-payment'),
    url(r'^(?P<pk>\d+)/paid/$', film_paid, name='film-paid'),

    # Film preview
    url(r'^(?P<film_id>\d+)/preview/$', preview_form_handler, name='film-preview-form-handler'),
    url(r'^preview/(?P<pk>\d+)/unlink/$', unlink_preview_file, name='unlink-preview-file'),

    # For browse page
    url(r'^by_letter/letter=(?P<letter>\w)$', films_by_letter, name='films-by-letter'),
    url(r'^(?P<film_id>\d+)/trailer/$', get_trailer_embed_code, name='film-get-trailer-embed-code'),
    url(r'^(?P<film_id>\d+)/preview_code/$', get_preview_embed_code, name='film-get-preview-embed-code'),

    # Film details (leave this last because of slug)
    url(r'^(?P<pk>\d+)/', film_details,  name='film-details'),

    # Tags
    url(r'^by_tag/tag=(?P<tag>.+)$', films_by_tag, name='films-by-tag'),
    url(r'^by_tag/$', films_by_tag, name='films-by-tag-search'),

)

screening/urls.py
from django.conf.urls.defaults import patterns, url

from .views import *

urlpatterns = patterns(
    '',
    url(r'^add/$', create_screening, name='add-screening'),
    url(r'^(?P<pk>\d+)/$', view_screening, name='screening-details'),
    url(r'^(?P<pk>\d+)/public/$', screening_page, name='screening-page'),
    url(r'^(?P<pk>\d+)/accept/$', accept_screening, name='accept-screening'),
    url(r'^(?P<pk>\d+)/decline/$', decline_screening, name='decline-screening'),
    url(r'^(?P<pk>\d+)/cancel/$', cancel_screening, name='cancel-screening'),
    url(r'^(?P<pk>\d+)/pay/$', screening_payment_form, name='screening-payment'),
    url(r'^(?P<pk>\d+)/paid/$', screening_paid, name='screening-paid'),

    url(r'^(?P<pk>\d+)/edit/$', create_screening, name='edit-screening'),
    url(r'^(?P<pk>\d+)/report/add/$', create_screening_report, name='create-screening-report'),
    url(r'^(?P<pk>\d+)/report/add/$', create_screening_report, name='edit-screening-report'),
    url(r'^(?P<pk>\d+)/report/photo/upload/$', upload_screening_report_photo, name='upload-screening-report-photo'),
    url(r'^(?P<pk>\d+)/report/photo/remove/$', remove_screening_report_photo, name='remove-screening-report-photo'),
    url(r'^(?P<pk>\d+)/report/film_owner/$', fill_screening_report, name='fill-screening-report'),
)

screening/models.py
import hashlib
import datetime
import random
import pytz
from django.db import models
from django.db.models import Q, Count
from django.contrib.auth.models import User
from copy import deepcopy
from pytz import timezone

from common.models import Country
from film.models import Film
from notifications.models import NewsItem, NewsItemType


class ActiveVenuesManager(models.Manager):
    def get_query_set(self):
        return super(ActiveVenuesManager, self).get_query_set().filter(deleted=False)


class Venue(models.Model):
    TIMEZONES = map(lambda tz: (tz, tz.replace('_', ' ')), pytz.common_timezones)

    name = models.CharField(max_length=250)
    # street_address = models.CharField(max_length=250, null=True, blank=True)
    city = models.CharField(max_length=250, null=True, blank=True)
    county = models.CharField(max_length=250, null=True, blank=True)
    state = models.CharField(max_length=250, null=True, blank=True)
    country = models.ForeignKey(Country)
    timezone = models.CharField(max_length=100, choices=TIMEZONES)
    phone_number = models.TextField(max_length=30, null=True, blank=True)
    # email = models.TextField(max_length=250, null=True, blank=True)
    # google_or_yelp = models.URLField(max_length=250, null=True, blank=True)
    website = models.URLField(max_length=250, null=True, blank=True)
    description = models.TextField()
    deleted = models.BooleanField(default=False)
    # profile_image = models.ImageField(upload_to='venues/profile_images', null=True, blank=True)
    #is_verified = models.BooleanField(default=False)
    user = models.ForeignKey(User, related_name='venues')

    objects = models.Manager()
    active = ActiveVenuesManager()

    def __unicode__(self):
        return self.name

    def model_class(self):
        return 'Venue'

    def belongs_to(self, user):
        return True if self.user == user else False

    @property
    def metadesc(self):
        return ','.join([self.name, self.street_address, self.city, self.country.name, self.description])

    @staticmethod
    def by_user(user):
        return Venue.active.filter(user=user)

    def url_service(self):
        if self.google_or_yelp.startswith('http://www.google.com'):
            return 'GOOGLE'
        elif self.google_or_yelp.startswith('http://www.yelp.com'):
            return 'YELP'
        return 'REVIEW'

    @staticmethod
    def get_with_film_count(min_length, max_length, min_year, max_year, country_id):
        if country_id != 'all':
            venues = Venue.active.filter(
                screenings__cancelled=False,
                screenings__decision='APPROVED',
                films__film__runtime__range=(min_length, max_length),
                films__film__year__range=(min_year, max_year),
                films__film__is_public=True,
                films__film__deleted=False,
                films__film__countries__pk=country_id
            )
        else:
            venues = Venue.active.filter(
                screenings__cancelled=False,
                screenings__decision='APPROVED',
                films__film__runtime__range=(min_length, max_length),
                films__film__year__range=(min_year, max_year),
                films__film__is_public=True,
                films__film__deleted=False
            )

        return venues.annotate(screening_count=Count('screenings')).annotate(film_count=Count('screenings__film', distinct=True))

    def get_random_film(self):
        return random.choice(self.films.all()).film if self.films.count() else None

    @property
    def public_screenings(self):
        return [s for s in self.screenings.all() if s.is_published and s.film.is_public]

    def has_in_progress_screening_of(self, film):
        for screening in self.screenings.all():
            if screening.is_accepted and screening.film == film and not screening.is_published:
                return True

        return False

    @staticmethod
    def have_shown(film_id):
        """
        Returns all venues that have a published screening for given film.
        """
        film = Film.active.get(pk=film_id)
        screenings = Screening.objects.filter(film=film)
        screenings = [s for s in screenings if s.is_published]
        return [s.venue for s in screenings]


class FilmOnVenue(models.Model):
    VENUE_START_YEAR = 1932
    VENUE_END_YEAR = 2015
    VENUE_YEARS = zip(
        range(VENUE_START_YEAR, VENUE_END_YEAR + 1),
        range(VENUE_START_YEAR, VENUE_END_YEAR + 1)
    )

    section = models.CharField(max_length=200, null=True, blank=True)
    awards = models.CharField(max_length=200, null=True, blank=True)
    venue = models.ForeignKey(Venue, related_name='films')
    year = models.PositiveIntegerField(choices=VENUE_YEARS, null=True, blank=True)
    film = models.ForeignKey(Film, related_name='venues')

    def __unicode__(self):
        return self.film.title + ' on ' + self.venue.name


class ProfitShare(models.Model):
    TYPES = (
        ('NOPROFIT', 'No profit'),
        ('SHARE', 'Share'),
        ('UPFRONT', 'Up front')
    )
    # These two are percentages, used when type == 'SHARE'
    film_share = models.IntegerField(null=True, blank=True)
    smplmchn_share = models.IntegerField(null=True, blank=True)

    # These two are exact amounts, used when type == 'UPFRONT'
    film_upfront = models.DecimalField(null=True, blank=True, max_digits=12, decimal_places=2)
    smplmchn_upfront = models.DecimalField(null=True, blank=True, max_digits=12, decimal_places=2)
    type = models.CharField(max_length=20, choices=TYPES)

    def __unicode__(self):
        return self.type

    @property
    def venue_share(self):
        if self.film_share and self.smplmchn_share:
            return 100 - self.film_share - self.smplmchn_share
        return None

    @property
    def venue_upfront(self):
        if self.film_upfront and self.smplmchn_upfront:
            return self.film_upfront + self.smplmchn_upfront
        return None


class ScreeningReport(models.Model):
    description = models.TextField()
    total_revenue = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return 'Yes ($' + str(self.total_revenue) + ')' if self.total_revenue else 'Yes'


class ScreeningReportFilmOwner(models.Model):
    PAID_PROMPTLY = (
        ('YES', 'Yes'),
        ('KINDA', 'Kinda'),
        ('NO', 'No')
    )
    RECOMMEND_VENUE = (
        ('YES', 'Yes'),
        ('EH', 'Eh'),
        ('NO', 'No')
    )
    REPORT_FRAUD = (
        ('YES', 'Yes'),
        ('NO', 'No')
    )

    description = models.TextField()
    paid_promptly = models.CharField(max_length=20, choices=PAID_PROMPTLY, blank=True, null=True)
    recommend_venue = models.CharField(max_length=20, choices=RECOMMEND_VENUE)
    report_fraud = models.CharField(max_length=20, choices=REPORT_FRAUD)


class Screening(models.Model):
    DECISIONS = (
        ('APPROVED', 'Approved'),
        ('DECLINED', 'Declined')
    )

    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    venue = models.ForeignKey(Venue, related_name='screenings')
    film = models.ForeignKey(Film, related_name='screenings')
    decision = models.CharField(max_length=20, choices=DECISIONS, null=True, blank=True)
    profit = models.OneToOneField(ProfitShare, related_name='screening', null=True, blank=True)
    cancelled = models.BooleanField(default=False)
    report = models.OneToOneField(ScreeningReport, null=True, blank=True)
    film_report = models.OneToOneField(ScreeningReportFilmOwner, null=True, blank=True)
    paid = models.BooleanField(default=False)

    def __unicode__(self):
        return self.film.title + ' @ ' + self.venue.name + '(' + str(self.id) + ')'

    @staticmethod
    def all_published():
        screenings = Screening.objects.filter(cancelled=False).all()
        return [s for s in screenings if s.is_published]

    @staticmethod
    def all_valid():
        screenings = Screening.objects.filter(cancelled=False).all()
        return [s for s in screenings if s.is_accepted]

    @staticmethod
    def for_user(user):
        return Screening.objects.filter(
            (Q(venue__user = user) | Q(film__user = user)) & Q(cancelled = False)
        ).prefetch_related('schedule')

    @property
    def title(self):
        return self.film.title + " @ " + self.venue.name

    @property
    def decision_made(self):
        return True if self.decision else False

    def approve(self):
        self.decision = 'APPROVED'

    def decline(self):
        self.decision = 'DECLINED'

    @property
    def is_accepted(self):
        return self.decision == 'APPROVED'

    @property
    def is_declined(self):
        return self.decision == 'DECLINED'

    @property
    def is_updated(self):
        film_owner_message = NewsItem.get_for_user(
            self.film.user,
            NewsItemType.SCREENING_UPDATED,
            object=self
        )
        return True if film_owner_message else False

    def cancel(self):
        self.cancelled = True

    def add_screening_at(self, t):
        if not self.schedule.filter(time=t).exists():
            self.schedule.add(ScreeningEvent(screening=self, time=t))

    @property
    def film_owners_earning(self):
        if self.profit.type == 'UPFRONT':
            return float(self.profit.film_upfront)
        elif self.profit.type == 'SHARE':
            if not self.report or not self.report.total_revenue:
                return None
            return float(self.report.total_revenue * (float(self.profit.film_share)/100))

    @property
    def simplemachine_earning(self):
        if self.profit.type == 'UPFRONT':
            return float(self.profit.smplmchn_upfront)
        elif self.profit.type == 'SHARE':
            if not self.report or not self.report.total_revenue:
                return None
            return float(self.report.total_revenue * (float(self.profit.smplmchn_share)/100))

screening/templates/events_list.html
{% extends "base.html" %}

{% block title %}Events!{% endblock %}
    
{% block content %}
</div>
<div id="pg_events-list">

<nav class="dash">
    <a href="#future">FUTURE EVENTS</a>
    <a href="#past" class="active">PAST EVENTS</a>
</nav>

<div id="future" class="events-list" style="display: none" >  
    <section class="event-timeline">
    {% for screening in future %}  
        {% include "partials/_event_module.html" with screening=screening %}
    {% endfor %}
    </section>  
</div>

<div id="past" class="events-list active">
    <section class="event-timeline">
    {% for screening in past %}  
        {% include "partials/_event_module.html" with screening=screening %}
    {% endfor %}
    </section>  
</div>    

</div>    
    
{% endblock %}

{% block extra_js %}

<script type="text/javascript">
    $(document).ready(function () {
        $("nav.dash a").on("click", function(e){
            e.stopPropagation();
            e.preventDefault();
            var current_el = $(this);
            $("nav.dash a").removeClass("active");
            current_el.addClass("active");
            $("div.events-list").hide()
            $(current_el.attr('href')).show();
            return false;
        });
    });
</script>    
{% endblock %}

screening/templates/screening_form.html
{% extends "base.html" %}
{% load common_tags %}


{% block content %}
<div id="pg--screening-form">

<div class="page-title">
    <h1>NEW SCREENING</h1>
</div>

    <form action="." method="post" id="create-screening-form">
        {{ form.screening_times }}
        {{ form.profit_share_type }}
        {{ form.profit_share_amounts }}

        {% csrf_token %}

        <h2>WHAT ARE YOU SHOWING?</h2>
        <div class="what">
            {% with field=form.film %}
                {% include "helpers/form_field.html" %}
            {% endwith %}
        </div>


        <h2>WHERE WILL YOU SHOW IT?</h2>

        <div class="where">
        {% if has_venues %}
            {% with field=form.venue %}
                {% include "helpers/form_field.html" %}
            {% endwith %}
        {% else %}
            {% if form.venue.errors %}
            {% endif %}
            <a href="{% url "add-venue" %}">+ CREATE NEW VENUE</a>
        {% endif %}
        </div>

        <h2>WHEN?</h2>

        <div class="when control-group {% if form.screening_times.errors %}  error {% endif %}" id="times">
            <div id="defined-screenings">
            </div>
            <div class="date-time-picker" id="date-time-picker">
                <input type="text" name="screening_date" placeholder="DATE *" class="datepicker"/>
                <input type="text" name="screening_time" placeholder="TIME (24:00) *" />
            </div>
            {% if form.screening_times.errors %}
                <span class="help-block">
                    <!-- How would there be multiple errors? We are checking for errors via JS after every entry! Is this outdated? -->
                    {% for e in form.screening_times.errors %}{{ e }}{% if not forloop.last %}, {% endif %}{% endfor%}
                </span>
            {% endif %}
            <button class="add-screening" id="add-screening" type="button">+ADDITIONAL SCREENING</button>
        </div>


        <h2>WHAT DOES THE FILM NEED TO KNOW?</h2>
        <div class="description">
            {% with field=form.description %}
                {% include "helpers/form_field.html" %}
            {% endwith %}
        </div>

        <h2>AND HOW WILL YOU PAY THE FILM?</h2>

            <div class="payment-options" id="profit_share">
                <button type="button" id="SHARE">PROFIT SHARE</button>
                <button type="button" id="UPFRONT">UP-FRONT</button>
                <button type="button" id="NOPROFIT">NO PROFIT</button>
            </div>

            <div class="payment {% if form.errors.profit_share_type %} control-group error {% endif %}">
                <div id="amounts-share" style="display: none;">
                    {% if form.errors.profit_share_type %}
                        <span class="help-block">{{ form.errors.profit_share_type|first }}</span>
                    {% endif %}
                    <table>
                        <tr>
                            <td>FILM </td>
                            <td>
                                {% with field=form.share_film %}
                                    {% include "helpers/form_field.html" %}
                                {% endwith %}
                            </td>
                            <td> % </td>
                        </tr>
                        <tr>
                            <td>SMPLMCHN </td>
                            <td class="sm-percentage">{{ sm_percentage }}</td>
                            <td> % </td>
                        </tr>
                        <tr>
                            <td>VENUE </td>
                            <td>
                                {% with field=form.share_venue %}
                                    {% include "helpers/form_field.html" %}
                                {% endwith %}
                            </td>
                            <td> % </td>
                        </tr>
                    </table>
                </div>
                <div id="amounts-upfront" style="display: none;">
                    {% if form.errors.profit_share_type %}
                        <span class="help-block">{{ form.errors.profit_share_type|first }}</span>
                    {% endif %}
                    <table>
                        <tr>
                            <td>FILM GETS </td>
                            <td> $ </td>
                            <td>
                                {% with field=form.upfront_film %}
                                    {% include "helpers/form_field.html" %}
                                {% endwith %}
                            </td>
                             <!-- SPACER Keeps things even with previous table -->
                        </tr>
                        <tr>
                            <td>SMPLMCHN GETS </td>
                            <td> $ </td>
                            <td>
                                {% with field=form.upfront_smplmchn %}
                                    {% include "helpers/form_field.html" %}
                                {% endwith %}
                            </td>
                        </tr>
                        <tr>
                            <td>VENUE <span>PAYS</span> </td>
                            <td> $ </td>
                            <td>
                                {% with field=form.upfront_venue %}
                                    {% include "helpers/form_field.html" %}
                                {% endwith %}
                            </td>
                        </tr>
                    </table>
                </div>
                <div id="amounts-noprofit" style="display: none"></div>

            </div>
    </form>

    <div class="save">
        {% if form.instance.pk %}
            <button class="submit">UPDATE SCREENING INVITATION</button>
        {% else %}
            <button class="submit">SUBMIT SCREENING INVITATION</button>
        {% endif %}
    </div>


</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    var selectProfitType = function(type){
        $("form input#profit-share-type-id").val(type);
        $("div#profit_share button").removeClass('active');
        $("#"+type).addClass('active');


        if (type != 'NOPROFIT'){
            if (type == 'SHARE'){
                $("div#amounts-share").show();
                $("div#amounts-upfront").hide();
                $("div#amounts-noprofit").hide();
            }
            else {
                $("div#amounts-share").hide();
                $("div#amounts-upfront").show();
                $("div#amounts-noprofit").hide();
            }
        } else {
            $("div#amounts-share").hide();
            $("div#amounts-upfront").hide();
            $("div#amounts-noprofit").show();
        }
    };

    $(window).ready(function(){
        $("#id_upfront_venue").attr("readonly", "readonly");
        $("#id_upfront_smplmchn").attr("readonly", "readonly");
        $("#id_share_venue").attr("readonly", "readonly");

    {% if is_paid %}
        $("div.payment-options button").prop('disabled', 'disabled');
        $("div#amounts-upfront input").prop('readonly', 'readonly')
    {% endif %}

        $(".submit").on("click", function(e){
            var dateField = $("form input[name='screening_date']")
            var timeField = $("form input[name='screening_time']")
            if (dateField.val() || timeField.val()) {
                addFromDateAndTimeFields();
            }
            $("form#create-screening-form").submit();
        });

        if ("{{ form.profit_film.value }}" != "") {
            $("div#profit_share_amounts input[name='profit-film']").val("{{ form.profit_film.value }}");
        };



        $("#id_upfront_film").blur(function(ev){
            var film_gets = parseFloat($("#id_upfront_film").val());
            var sm_gets = film_gets / 100 * {{ sm_percentage }};
            sm_gets = sm_gets.toFixed(2);
            var venue_gives = parseFloat(film_gets) + parseFloat(sm_gets);
            venue_gives = venue_gives.toFixed(2);

            $("#id_upfront_smplmchn").val(sm_gets);
            $("#id_upfront_venue").val(venue_gives);
        });

        $("#id_share_film").blur(function(ev){
            var film_gets = parseFloat($("#id_share_film").val());
            var sm_gets = {{ sm_percentage }};
            sm_gets = sm_gets.toFixed(2);
            var venue_gives = 100 - sm_gets - film_gets;
            $("#id_share_venue").val(venue_gives);
        });

        var yesterday = new Date(); // this is today
        yesterday.setDate(new Date().getDate() - 1);
		$('.datepicker').datepicker({format: 'yyyy-mm-dd', autoclose:true, startDate: yesterday});

        SM.singleChoiceDropdown($("input#id_film"), '{% url "json-films" %}', true);
        {% if is_edit %}
        $('a.remove-selection').hide();
        {% endif %}

        SM.singleChoicePick($("select#id_venue"), "Create new venue...", "{% url "add-venue" %}");

        var addFromDateAndTimeFields = function() {
            // Remove current errors

            $("div#times").removeClass("error");
            $("div#times span").remove();

            // Append currently entered date and time to hidden field
            var dateField = $("form input[name='screening_date']")
            var timeField = $("form input[name='screening_time']")
            var current_dates = $("input#screening-times-id").val();
            var date = dateFromMultipleFields(dateField, timeField);
            if (date == "Invalid Date") {
                $("div#times").addClass("error");
                $("div#date-time-picker").after("<span class='help-block'>Please enter time in 24-hour format, eg. 19:30</span>");
            };

            $("input#screening-times-id").val(current_dates + ";" + date.toISOString());
            var timestamp = date.getTime();
            $("div#defined-screenings").append("<p data-timestamp='" + timestamp + "' class='selected-screening-time'>" + smDateTimeFormat(date) + " <button class='delete-screening' type='button'>-DELETE</button></p>");

            dateField.val("");
            timeField.val("");
        };

        // Screening dates handling
        $("button#add-screening").on("click", function(){
            addFromDateAndTimeFields();
        });

        $("div#defined-screenings").on("click", "button.delete-screening", function(elem){
            $(elem.target).parent().remove();
            var new_current_dates = [];
            $("div#defined-screenings p[data-timestamp]").each(function(){
                var timestamp = $(this).attr('data-timestamp');
                var date_to_add = new Date(parseInt(timestamp)).toISOString();
                new_current_dates.push(date_to_add);
            })
            $("input#screening-times-id").val(new_current_dates.join(';'));
        });

        $("div#profit_share button").on("click", function(e) {
            e.preventDefault();
            selectProfitType(e.target.id);
        });

        selectProfitType($("form input#profit-share-type-id").val());

        // TODO: extract to utils.js
        var dateFromMultipleFields = function(dateField, timeField){
            var date = new Date(
                dateField.val().split('-')[0],
                dateField.val().split('-')[1]-1,
                dateField.val().split('-')[2],
                timeField.val().split(':')[0],
                timeField.val().split(':')[1]
            );
            return date;
        };

        var pad = function(n){
            return n<10 ? '0'+n : n;
        }

        var smDateTimeFormat = function(d) {
            var hours = d.getHours();
            var ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12;
            hours = hours ? hours : 12; // the hour '0' should be '12'
            return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+' @ '+pad(hours)+':'+pad(d.getMinutes())+ampm;
        };

        var defined_screenings = "{{ form.screening_times.value }}";
        if (defined_screenings != "None") {
            _.each(defined_screenings.split(';'), function(screening){
                if (screening != '') {
                    var screening_date = new Date(screening);
                    var timestamp = screening_date.getTime();
                    $("div#defined-screenings").append("<p data-timestamp='" + timestamp + "' style='font-size: 1.5em'>" + smDateTimeFormat(screening_date) + " <button class='delete-screening' type='button'>-DELETE</button></p>");
                }
            });
        };
    });
</script>
{% endblock %}