film/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *


urlpatterns = patterns(
    '',
    url(r'^search/$', search_films_json,  name='json-films'),

    # Dropbox
    url(r'^(?P<pk>\d+)/upload/dropbox/$', upload_from_dropbox,  name='upload-from-dropbox'),
    url(r'^(?P<pk>\d+)/upload/dropbox/progress/$', dropbox_upload_progress, name='dropbox-upload-progress'),
    url(r'^(?P<pk>\d+)/upload/dropbox/cancel/$', cancel_dropbox_upload,  name='cancel-dropbox-upload'),

    # Add and edit
    url(r'^add/$', add_film, name='add-film'),
    url(r'^add/(?P<pk>\d+)/media/$', add_film_media, name='add-film-media'),
    url(r'^add/(?P<pk>\d+)/festivals/$', add_film_festivals, name='add-film-festivals'),
    url(r'^add/(?P<pk>\d+)/reviews/$', add_film_reviews, name='add-film-reviews'),
    url(r'^add/(?P<pk>\d+)/cast/$', add_film_cast, name='add-film-cast'),
    url(r'^add/(?P<pk>\d+)/logistics/$', add_film_logistics, name='add-film-logistics'),
    # url(r'^imdb_info/$', get_imdb_info, name='imdb-info'),
    url(r'^(?P<pk>\d+)/edit/$', edit_film, name='edit-film'),
    url(r'^(?P<pk>\d+)/delete/$', delete_film, name='delete-film'),

    # Festivals
    url(r'^add/festivals/add-film/$', add_film_on_festival, name='add-film-on-festival'),
    # url(r'^festival/ajax/create/$', add_festival, name='add-festival'),
    # url(r'^festivals/(?P<pk>\d+)/$', festival_details,  name='festival-details'),
    # url(r'^festivals/delete/$', delete_fof,  name='delete-fof'),
    # url(r'^festivals/$', list_festivals, name='list-festivals'),

    # Stills
    url(r'^(?P<pk>\d+)/stills/upload/$', upload_still_image, name='upload-film-still'),
    url(r'^stills/remove/$', remove_still, name='remove-still'),

    # Files
    url(r'^(?P<pk>\d+)/files/exhibition/$', upload_exhibition_file, name='upload-exhibition-file'),
    url(r'^(?P<pk>\d+)/files/exhibition/download/$', download_exhibition_file, name='download-exhibition-file'),
    url(r'^(?P<pk>\d+)/files/exhibition/ftp-download/$', download_exhibition_file_ftp, name='download-exhibition-file-ftp'),
    url(r'^(?P<pk>\d+)/files/exhibition/dropbox-download/$', download_exhibition_file_dropbox, name='download-exhibition-file-dropbox'),
    url(r'^(?P<pk>\d+)/files/exhibition/ftp_upload_info/$', ftp_upload_info, name='ftp-upload-info'),
    url(r'^users_dropbox_files/$', users_dropbox_files, name='users-dropbox-files'),

    # Reviews
    url(r'^(?P<film_id>\d+)/reviews/add/$', add_review, name='add-review'),
    url(r'^reviews/delete/$', delete_review, name='delete-review'),

    # Cast & Crew
    url(r'^(?P<film_pk>\d+)/cast/add/$', add_cast, name='add-cast'),
    url(r'^(?P<film_pk>\d+)/crew/add/$', add_crew, name='add-crew'),
    url(r'^(?P<film_pk>\d+)/cast/(?P<cast_pk>\d+)/delete/$', delete_cast,  name='delete-cast'),
    url(r'^(?P<film_pk>\d+)/crew/(?P<crew_pk>\d+)/delete/$', delete_crew,  name='delete-crew'),

    # PreviewRequest
    url(r'^(?P<pk>\d+)/preview_request/$', send_preview_request, name='send-preview-request'),
    url(r'^(?P<film_id>\d+)/preview_request/(?P<prev_req_id>\d+)/accept/$', accept_preview_request, name='film-accept-preview-request'),
    url(r'^(?P<film_id>\d+)/preview_request/(?P<prev_req_id>\d+)/decline/$', decline_preview_request, name='film-decline-preview-request'),

    # DownloadRequest
    url(r'^(?P<pk>\d+)/download_request/$', send_download_request, name='send-download-request'),
    url(r'^(?P<film_id>\d+)/download_request/(?P<down_req_id>\d+)/accept/$', accept_download_request, name='film-accept-download-request'),
    url(r'^(?P<film_id>\d+)/download_request/(?P<down_req_id>\d+)/decline/$', decline_download_request, name='film-decline-download-request'),

    # Film payment
    url(r'^(?P<pk>\d+)/payment/$', film_payment, name='film-payment'),
    url(r'^(?P<pk>\d+)/paid/$', film_paid, name='film-paid'),

    # Film preview
    url(r'^(?P<film_id>\d+)/preview/$', preview_form_handler, name='film-preview-form-handler'),
    url(r'^preview/(?P<pk>\d+)/unlink/$', unlink_preview_file, name='unlink-preview-file'),

    # For browse page
    url(r'^by_letter/letter=(?P<letter>\w)$', films_by_letter, name='films-by-letter'),
    url(r'^(?P<film_id>\d+)/trailer/$', get_trailer_embed_code, name='film-get-trailer-embed-code'),
    url(r'^(?P<film_id>\d+)/preview_code/$', get_preview_embed_code, name='film-get-preview-embed-code'),

    # Film details (leave this last because of slug)
    url(r'^(?P<pk>\d+)/', film_details,  name='film-details'),

    # Tags
    url(r'^by_tag/tag=(?P<tag>.+)$', films_by_tag, name='films-by-tag'),
    url(r'^by_tag/$', films_by_tag, name='films-by-tag-search'),

)

online_screening/urls.py
from django.conf.urls.defaults import patterns, url

from .views import *

urlpatterns = patterns(
    '',
    url(r'^add/$', create_online_screening, name='add-online-screening'),
    url(r'^edit/(?P<pk>\d+)/$', create_online_screening, name='edit-online-screening'),
    url(r'^cancel/(?P<pk>\d+)/$', cancel_online_screening, name='cancel-online-screening'),
    url(r'^(?P<pk>\d+)/$', view_online_screening, name='online-screening-details'),
    url(r'^(?P<invite_hash>.+)/invitation/$', create_online_film, name='create-online-film'),
    url(r'^(?P<online_screening_id>\d+)/remove_film/(?P<vimeo_video_id>\d+)/$', delete_online_film, name='delete-online-film'),
)

online_screening/models.py
import hashlib
import datetime
import pytz

from pytz import timezone
from django.db import models
from django.contrib.auth.models import User


class OnlineScreening(models.Model):
    TIMEZONES = map(lambda tz: (tz, tz.replace('_', ' ')), pytz.common_timezones)

    name = models.CharField(max_length=200)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    timezone = models.CharField(max_length=100, choices=TIMEZONES)
    user = models.ForeignKey(User, related_name='online_screenings')
    invite_hash = models.URLField(max_length=250, unique=True)
    cancelled = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    is_ready = models.BooleanField(default=False)

    def __unicode__(self):
        return self.invite_hash

    @staticmethod
    def _generate_invite_hash(user):
        m = hashlib.md5()
        m.update("%s%s" % (user.email, datetime.datetime.now()))
        return m.hexdigest()

    @staticmethod
    def get_by_hash(invite_hash):
        return OnlineScreening.objects.filter(
            OnlineScreening.cancelled==False
        ).filter(OnlineScreening.invite_hash==invite_hash).first()

    @property
    def is_started(self):
        now = datetime.datetime.now(pytz.utc)
        return True if now > self.start_time else False

    def check_if_film_already_exists(self, vimeo_id):
        if vimeo_id in [film.vimeo_id for film in self.online_films.all()]:
            return True
        else:
            return False

    def cancel(self):
        self.cancelled = True


class OnlineFilm(models.Model):
    user = models.ForeignKey(User, related_name='online_films')
    online_screening = models.ForeignKey(OnlineScreening, related_name='online_films')
    vimeo_id = models.CharField(max_length=20, blank=True)
    vimeo_password = models.CharField(max_length=50, blank=True)
    vimeo_privacy = models.CharField(max_length=10, blank=True)
    vimeo_embed_privacy = models.CharField(max_length=10, blank=True)
    is_ready = models.BooleanField(default=False)

online_screening/forms.py
import datetime
import pytz

from dateutil import parser as iso8601_parser
from django import forms
from pytz import timezone
from django_select2.widgets import Select2Widget
from django_select2.fields import Select2ChoiceField

from .models import OnlineScreening, OnlineFilm


class OnlineScreeningForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'TITLE *'}), required=True)
    start_time = forms.CharField(widget=forms.HiddenInput(), required=True)
    end_time = forms.CharField(widget=forms.HiddenInput(), required=True)
    timezone = Select2ChoiceField(
        required=True,
        choices=[('', '')] + OnlineScreening.TIMEZONES,
        widget=Select2Widget(select2_options={'placeholder': 'TIMEZONE *'})
    )

    def clean(self):
        self.cleaned_data['start_time'] = self._clean_time(self.cleaned_data['start_time'])
        self.cleaned_data['end_time'] = self._clean_time(self.cleaned_data['end_time'])
        return self.cleaned_data

    def _clean_time(self, field):
        if field:
            try:
                dt = iso8601_parser.parse(field)
                now = datetime.datetime.now(timezone(self.cleaned_data['timezone']))
                if dt < now:
                    raise forms.ValidationError('Invalid online screening date or time')
                field = dt
            except:
                raise forms.ValidationError('Invalid online screening date or time')
        return field

    class Meta:
        model = OnlineScreening
        exclude = ('user', 'invite_hash', 'cancelled', 'created_on', 'is_ready')



class OnlineFilmForm(forms.ModelForm):
    class Meta:
        model = OnlineFilm
        exclude = ('user', 'online_screening', 'is_ready')
        widgets = {
            'vimeo_id': forms.HiddenInput(),
            'vimeo_password': forms.TextInput(attrs={'placeholder': 'VIMEO VIDEO PASSWORD *'}),
            'vimeo_privacy': forms.HiddenInput(),
            'vimeo_embed_privacy': forms.HiddenInput()
        }

online_screening/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404

from common.vimeo_api import VimeoAPI
from .models import OnlineScreening, OnlineFilm
from .forms import OnlineScreeningForm, OnlineFilmForm

@login_required
def create_online_screening(request, pk=None):
    if pk:
        online_screening = get_object_or_404(OnlineScreening, pk=pk)
        form = OnlineScreeningForm(request.POST or None, instance=online_screening)
    else:
        online_screening = None
        form = OnlineScreeningForm(request.POST or None)

    if form.is_valid():
        form.instance.user = request.user
        form.instance.invite_hash = OnlineScreening._generate_invite_hash(request.user)
        new_online_screening = form.save()
        if online_screening:
            messages.success(request, 'Online screening updated!')
        else:
            messages.success(request, 'Online screening created!')
        return redirect('online-screening-details', new_online_screening.pk)

    edit = True if online_screening else False

    return render(request, 'online_screening_form.html', {
        'form': form,
        'edit': edit
    })


def view_online_screening(request, pk):
    online_screening = get_object_or_404(OnlineScreening, pk=pk)
    if online_screening.cancelled:
        return redirect('home')
    online_screening_url = request.build_absolute_uri(reverse('create-online-film', args=(online_screening.invite_hash,)))
    return render(request, 'online_screening_details.html', {
        'online_screening': online_screening,
        'online_screening_url': online_screening_url
    })


@login_required
def create_online_film(request, invite_hash):
    if request.user.get_profile().is_linked_with_vimeo():
        vimeo_videos = VimeoAPI.get_user_videos(request.user.get_profile().vimeo_access_token)
        online_screening = get_object_or_404(OnlineScreening, invite_hash=invite_hash)
        if online_screening.is_started:
            return redirect('online-screening-details', pk=online_screening.pk)
        is_pro = vimeo_videos[0].get('owner').get('is_pro') if vimeo_videos else None

        form = OnlineFilmForm(request.POST or None)

        if form.is_valid():
            form.instance.user = request.user
            form.instance.online_screening = online_screening
            new_online_film = form.save()
            messages.success(request, 'Film added to online screening!')

        available_videos = []
        unavailable_videos = []
        already_added = []
        for video in vimeo_videos:
            video['thumbnail'] = video.get('thumbnails').get('thumbnail')[2].get('_content')
            if online_screening.check_if_film_already_exists(video.get('id')):
                already_added.append(video)
            elif video.get('embed_privacy') == 'anywhere' or is_pro == '1':
                available_videos.append(video)
            else:
                unavailable_videos.append(video)

        return render(request, 'online_film_form.html', {
            'online_screening': online_screening,
            'available_videos': available_videos,
            'unavailable_videos': unavailable_videos,
            'already_added_videos': already_added,
            'form': form,
            'is_pro': is_pro
        })
    else:
        return redirect("%s?next=%s" % (reverse('account-vimeo'), request.path))


@login_required
def cancel_online_screening(request, pk):
    online_screening = get_object_or_404(OnlineScreening, pk=pk)
    if not online_screening.user == request.user:
        return redirect('home')

    if online_screening.user == request.user:
        online_screening.cancel()
        online_screening.save()

    return render(request, 'online_screening_details.html', {
        'online_screening': online_screening
    })


@login_required
def delete_online_film(request, online_screening_id, vimeo_video_id):
    online_screening = get_object_or_404(OnlineScreening, pk=online_screening_id)
    try:
        online_film = OnlineFilm.objects.filter(vimeo_id=vimeo_video_id, online_screening__id=online_screening_id)[:1].get()
    except ObjectDoesNotExist:
        raise Http404

    if online_film and not online_film.user == request.user:
        return redirect('home')

    if online_film and online_film.user == request.user:
        online_film.delete()
    return redirect(reverse('create-online-film', args=(online_screening.invite_hash,)))

online_screening/templates/online_film_form.html
{% extends "base.html" %}
{% load common_tags %}

{% block content %}

<div id="pg--online-film-form">

    <div class="page-title">
        <h1>ADD FILM TO ONLINE FESTIVAL</h1>
    </div>

    <div class="field">
        <form id="add-online-film-form" action="." method="POST" class="form-horizontal">
            {% csrf_token %}

            {% if available_videos %}
            <div class="available-videos">
                <h2>CHOOSE A VIDEO:</h2>
                <div class="videos">
                    {% for video in available_videos %}
                        <div class="video-box">
                            <a class="vimeo-video" href="#" data-vimeo-id="{{ video.id }}" data-privacy="{{ video.privacy }}" data-embed-privacy="{{ video.embed_privacy }}">
                                <div class='thumb' style="background-image: url('{{ video.thumbnail }}');"></div>
                                <p>{{ video.title }}</p>
                            </a>
                        </div>
                    {% endfor %}
                    <div style="clear:both"></div>
                </div>
            </div>
            {% endif %}

            {% if unavailable_videos %}
            <div class="unavailable-videos">
                <h2>UNAVAILABLE VIDEOS
                <span> We noticed that you also have these videos on your Vimeo account, but you can't select them for a screening until you change the embed privacy to 'anywhere'.</span>
                </h2>
                <div class="videos">
                    {% for video in unavailable_videos %}
                        <div class="video-box">
                            <div class='thumb' style="background-image: url('{{ video.thumbnail }}');"></div>
                            <p>{{ video.title }}</p>
                        </div>
                    {% endfor %}
                    <div style="clear:both"></div>
                </div>
            </div>
            {% endif %}

            {% if already_added_videos %}
            <div class="added-videos">
                <h2>ADDED VIDEOS
                <span> These videos have been succesfully added to the online festival!</span>
                </h2>
                <div class="videos">
                    {% for video in already_added_videos %}
                        <div class="video-box">
                            <div class='thumb' style="background-image: url('{{ video.thumbnail }}');"></div>
                            <p>{{ video.title }}</p>
                            <a href="{% url "delete-online-film" online_screening.pk video.id %}">-REMOVE</a>
                        </div>
                    {% endfor %}
                    <div style="clear:both"></div>
                </div>
            </div>
            {% endif %}

            <div class="save">
            <a class="button" href="{% url 'online-screening-details' online_screening.pk %}">VIEW ONLINE SCREENING</a>
            </div>
            <div style="clear:both"></div>

            <div class="add-vimeo-video">
                <h2>ADD THIS VIDEO TO ONLINE SCREENING?</h2>
                {% render_form form %}
                <button id="make-public-yes" class="done" type="submit">+ADD</button>
                <button id="make-public-no" class="cancel" type="button">-CANCEL</button>

            </div>

        </form>
    </div>

</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    $(window).ready(function(){
        var is_pro = {{ is_pro }};
        $("input#id_vimeo_password").parent().parent().hide();
        $("div.add-vimeo-video").hide();

        $('a.vimeo-video').on('click', function(){
            var vimeo_id = $(this).attr('data-vimeo-id');
            var vimeo_privacy = $(this).attr('data-privacy');
            var vimeo_embed_privacy = $(this).attr('data-embed-privacy');

            $('a.selected-video').removeClass('selected-video');
            $(this).addClass('selected-video');
            $('input#id_vimeo_id').val(vimeo_id);
            $('input#id_vimeo_privacy').val(vimeo_privacy);
            $('input#id_vimeo_embed_privacy').val(vimeo_embed_privacy);

            if (vimeo_privacy == "password"){
                $("input#id_vimeo_password").parent().parent().show();
            }
            else {
                $("input#id_vimeo_password").parent().parent().hide();
            }
            $("div.add-vimeo-video").show();

            var thumbnail = $(this).find('div.thumb').clone();
            $("div.add-vimeo-video div.thumb").remove();
            $("div.add-vimeo-video h2").after(thumbnail);

            if (is_pro == 0 && vimeo_embed_privacy == 'nowhere') {
                SM.showMessage("error", "You have to change embed privacy for this video to 'anywhere' on your Vimeo or we won't be able to screen it!");
            };

            $('html, body').animate({
                scrollTop: $($("div.add-vimeo-video")).offset().top - parseInt($('body').css('paddingTop'))
            }, 500);

            return false;
        });

        $('html, body').animate({
            scrollTop: parseInt($('body').css('paddingTop'))
        }, 500);

        $("button.cancel").on('click', function(){
            window.location.reload();
        });

        $("form#add-online-film-form").submit(function(){
            $("input#id_vimeo_password").parents(".control-group").removeClass('error');
            if ($('input#id_vimeo_privacy').val() == "password" && !$("input#id_vimeo_password").val()){
                $("input#id_vimeo_password").parents(".control-group").addClass('error');
                return false;
            }
        });
    });
</script>
<style type="text/css">

</style>
{% endblock %}

online_screening/templates/online_screening_details.html
{% extends "base.html" %}
{% load tz %}

{% timezone online_screening.timezone %}

{% block title %}{% endblock %}

{% endtimezone %}

{% block content %}
</div>

<div id="pg--online-screening-details">

<div class="hero">
    <div class="title-container">
        <h1>ONLINE FESTIVAL</h1>
        <h2>
        by <a href="{% url "user-page" online_screening.user.id %}">{{ online_screening.user.get_profile.name|upper }}</a>
        <br />{{ online_screening.start_time|timezone:online_screening.timezone }} — {{ online_screening.end_time|timezone:online_screening.timezone }}
        </h2>
    </div>
</div>

{% if user == online_screening.user and not online_screening.is_started %}
<nav class="profile-menu">
    <a href="{% url "edit-online-screening" online_screening.id %}">EDIT ONLINE SCREENING</a>
    <a href="#link" class="menu-link">FILM INVITATION LINK</a>
    <div id="submenu" class="submenu" style="display: none">
        <div id="link" class="submenu-item" style="display: none">
        <p class="menu-text">
        Send the following URL to film-owners to invite films to this screening! They will be directed to link their Vimeo account and pick one or more of their videos to include.

        <p class="menu-text">{{ online_screening_url }}</p>
        </div>
        <button type="button" id="close-submenu">CLOSE</button>
    </div>

</nav>
{% endif %}

<div style="width: 65%; margin: auto; margin-top: 100px;">
    {% if online_screening.online_films.all %}
        {% for film in online_screening.online_films.all %}
            <div style="margin-bottom: 75px;">
            {% with id=film.vimeo_id %}
                {% include 'partials/_vimeo_embed_code.html' %}
            {% endwith %}
            </div>
        {% endfor %}
    {% else %}
        <p style="text-align: center">No films have been added yet! Anyone who visits the 'invitation link' can list their film on your screening, so only send it to those you are inviting! Films can be added any time before the screening begins, but not after. </p>
    {% endif %}
</div>

<div>

{% endblock %}


{% block extra_js %}
<script type="text/javascript">

     $("button#close-submenu").on("click", function(ev){
        $("div#submenu").hide();
        $("div#submenu > div").hide();
        $("a.menu-link").removeClass("active");
    });

    $("a.menu-link:not(.contact)").on("click", function(e){
        e.stopPropagation();
        e.preventDefault();
        var element_id = $(e.target).attr("href");
        $("div#submenu > div:not(" + element_id + ")").hide()
        $(element_id).toggle();
        $("a.menu-link").removeClass("active");
        if ($(element_id).css('display') != 'none'){
            $("div#submenu").show();
            $(e.target).addClass("active");
        }
        else {
            $("div#submenu").hide();
        }
        return false;
    });
</script>
{% endblock %}

online_screening/templates/online_screening_form.html
{% extends "base.html" %}
{% load common_tags %}

{% block content %}

<div id="pg--online-screening">

    <div class="page-title">
        {% if edit %}
            <h1>EDIT ONLINE SCREENING</h1>
        {% else %}
            <h1>NEW ONLINE SCREENING</h1>
        {% endif %}
    </div>

    <div class="fields">
        <form id="add-online-screening-form" action="." method="POST" class="form-horizontal">
            {% csrf_token %}
            {% render_form form %}

            <h2>START TIME</h2>
            <div class="when control-group {% if form.start_time.errors %} error {% endif %}" id="start-times">
                <div class="date-time-picker" id="start-date-time-picker">
                    <input type="text" name="start_date" placeholder="DATE *" class="datepicker"/>
                    <input type="text" name="start_clock" placeholder="TIME (24:00) *" />
                </div>
                <div style="clear: both"></div>
                {% if form.start_time.errors %}
                    <span class="help-block">
                        {% for e in form.start_time.errors %}{{ e }}{% if not forloop.last %}, {% endif %}{% endfor%}
                    </span>
                {% endif %}
            </div>

            <h2>END TIME</h2>
            <div class="when control-group {% if form.end_time.errors %} error {% endif %}" id="end-times">
                <div class="date-time-picker" id="end-date-time-picker">
                    <input type="text" name="end_date" placeholder="DATE *" class="datepicker"/>
                    <input type="text" name="end_clock" placeholder="TIME (24:00) *" />
                </div>
                <div style="clear: both"></div>
                {% if form.end_time.errors %}
                    <span class="help-block">
                        {% for e in form.end_time.errors %}{{ e }}{% if not forloop.last %}, {% endif %}{% endfor%}
                    </span>
                {% endif %}
            </div>

            <div class="save">
                <button class="submit">SAVE & FINISH </button>
            </div>

        </form>
    </div>

</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    var pad = function(n){
        return n<10 ? '0'+n : n;
    }

    // TODO: extract to utils.js
    var dateFromMultipleFields = function(dateField, timeField){
        var date = new Date(
            dateField.val().split('-')[0],
            dateField.val().split('-')[1]-1,
            dateField.val().split('-')[2],
            timeField.val().split(':')[0],
            timeField.val().split(':')[1]
        );
        return date;
    };

    $(window).ready(function(){
        $(".submit").on("click", function(e){
            var dateStartField = $("form input[name='start_date']");
            var timeStartField = $("form input[name='start_clock']");
            var dateEndField = $("form input[name='end_date']");
            var timeEndField = $("form input[name='end_clock']");
            var error = false;

            $("div#start-times span").remove();
            $("div#start-times").removeClass("error");
            var dateStart = dateFromMultipleFields(dateStartField, timeStartField);
            if (dateStart == "Invalid Date") {
                $("div#start-times").addClass("error");
                $("div#start-date-time-picker").after("<span class='help-block'>Please enter time in 24-hour format, eg. 19:30</span>");
                error = true;
            }

            $("div#end-times span").remove();
            $("div#end-times").removeClass("error");
            var dateEnd = dateFromMultipleFields(dateEndField, timeEndField);
            if (dateEnd == "Invalid Date") {
                $("div#end-times").addClass("error");
                $("div#end-date-time-picker").after("<span class='help-block'>Please enter time in 24-hour format, eg. 19:30</span>");
                error = true;
            }

            if (error == false){
                $("input#id_start_time").val(dateStart.toISOString());
                $("input#id_end_time").val(dateEnd.toISOString());
                $("form#add-curation-form").submit();
            }
            else {
                return false;
            }
        });

        if ($("input#id_start_time").val()){
            var startDate = new Date($("input#id_start_time").val());
            $("input[name='start_date']").val(startDate.getFullYear()+'-'+pad(startDate.getMonth()+1)+'-'+pad(startDate.getDate()));
            $("input[name='start_clock']").val(pad(startDate.getHours())+':'+pad(startDate.getMinutes()));
        }

        if ($("input#id_end_time").val()){
            var endDate = new Date($("input#id_end_time").val());
            $("input[name='end_date']").val(endDate.getFullYear()+'-'+pad(endDate.getMonth()+1)+'-'+pad(endDate.getDate()));
            $("input[name='end_clock']").val(pad(endDate.getHours())+':'+pad(endDate.getMinutes()));
        }
    });
</script>
{% endblock %}