film/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *


urlpatterns = patterns(
    '',
    url(r'^search/$', search_films_json,  name='json-films'),

    # Dropbox
    url(r'^(?P<pk>\d+)/upload/dropbox/$', upload_from_dropbox,  name='upload-from-dropbox'),
    url(r'^(?P<pk>\d+)/upload/dropbox/progress/$', dropbox_upload_progress, name='dropbox-upload-progress'),
    url(r'^(?P<pk>\d+)/upload/dropbox/cancel/$', cancel_dropbox_upload,  name='cancel-dropbox-upload'),

    # Add and edit
    url(r'^add/$', add_film, name='add-film'),
    url(r'^add/(?P<pk>\d+)/media/$', add_film_media, name='add-film-media'),
    url(r'^add/(?P<pk>\d+)/festivals/$', add_film_festivals, name='add-film-festivals'),
    url(r'^add/(?P<pk>\d+)/reviews/$', add_film_reviews, name='add-film-reviews'),
    url(r'^add/(?P<pk>\d+)/cast/$', add_film_cast, name='add-film-cast'),
    url(r'^add/(?P<pk>\d+)/logistics/$', add_film_logistics, name='add-film-logistics'),
    # url(r'^imdb_info/$', get_imdb_info, name='imdb-info'),
    url(r'^(?P<pk>\d+)/edit/$', edit_film, name='edit-film'),
    url(r'^(?P<pk>\d+)/delete/$', delete_film, name='delete-film'),

    # Festivals
    url(r'^add/festivals/add-film/$', add_film_on_festival, name='add-film-on-festival'),
    # url(r'^festival/ajax/create/$', add_festival, name='add-festival'),
    # url(r'^festivals/(?P<pk>\d+)/$', festival_details,  name='festival-details'),
    # url(r'^festivals/delete/$', delete_fof,  name='delete-fof'),
    # url(r'^festivals/$', list_festivals, name='list-festivals'),

    # Stills
    url(r'^(?P<pk>\d+)/stills/upload/$', upload_still_image, name='upload-film-still'),
    url(r'^stills/remove/$', remove_still, name='remove-still'),

    # Files
    url(r'^(?P<pk>\d+)/files/exhibition/$', upload_exhibition_file, name='upload-exhibition-file'),
    url(r'^(?P<pk>\d+)/files/exhibition/download/$', download_exhibition_file, name='download-exhibition-file'),
    url(r'^(?P<pk>\d+)/files/exhibition/ftp-download/$', download_exhibition_file_ftp, name='download-exhibition-file-ftp'),
    url(r'^(?P<pk>\d+)/files/exhibition/dropbox-download/$', download_exhibition_file_dropbox, name='download-exhibition-file-dropbox'),
    url(r'^(?P<pk>\d+)/files/exhibition/ftp_upload_info/$', ftp_upload_info, name='ftp-upload-info'),
    url(r'^users_dropbox_files/$', users_dropbox_files, name='users-dropbox-files'),

    # Reviews
    url(r'^(?P<film_id>\d+)/reviews/add/$', add_review, name='add-review'),
    url(r'^reviews/delete/$', delete_review, name='delete-review'),

    # Cast & Crew
    url(r'^(?P<film_pk>\d+)/cast/add/$', add_cast, name='add-cast'),
    url(r'^(?P<film_pk>\d+)/crew/add/$', add_crew, name='add-crew'),
    url(r'^(?P<film_pk>\d+)/cast/(?P<cast_pk>\d+)/delete/$', delete_cast,  name='delete-cast'),
    url(r'^(?P<film_pk>\d+)/crew/(?P<crew_pk>\d+)/delete/$', delete_crew,  name='delete-crew'),

    # PreviewRequest
    url(r'^(?P<pk>\d+)/preview_request/$', send_preview_request, name='send-preview-request'),
    url(r'^(?P<film_id>\d+)/preview_request/(?P<prev_req_id>\d+)/accept/$', accept_preview_request, name='film-accept-preview-request'),
    url(r'^(?P<film_id>\d+)/preview_request/(?P<prev_req_id>\d+)/decline/$', decline_preview_request, name='film-decline-preview-request'),

    # DownloadRequest
    url(r'^(?P<pk>\d+)/download_request/$', send_download_request, name='send-download-request'),
    url(r'^(?P<film_id>\d+)/download_request/(?P<down_req_id>\d+)/accept/$', accept_download_request, name='film-accept-download-request'),
    url(r'^(?P<film_id>\d+)/download_request/(?P<down_req_id>\d+)/decline/$', decline_download_request, name='film-decline-download-request'),

    # Film payment
    url(r'^(?P<pk>\d+)/payment/$', film_payment, name='film-payment'),
    url(r'^(?P<pk>\d+)/paid/$', film_paid, name='film-paid'),

    # Film preview
    url(r'^(?P<film_id>\d+)/preview/$', preview_form_handler, name='film-preview-form-handler'),
    url(r'^preview/(?P<pk>\d+)/unlink/$', unlink_preview_file, name='unlink-preview-file'),

    # For browse page
    url(r'^by_letter/letter=(?P<letter>\w)$', films_by_letter, name='films-by-letter'),
    url(r'^(?P<film_id>\d+)/trailer/$', get_trailer_embed_code, name='film-get-trailer-embed-code'),
    url(r'^(?P<film_id>\d+)/preview_code/$', get_preview_embed_code, name='film-get-preview-embed-code'),

    # Film details (leave this last because of slug)
    url(r'^(?P<pk>\d+)/', film_details,  name='film-details'),

    # Tags
    url(r'^by_tag/tag=(?P<tag>.+)$', films_by_tag, name='films-by-tag'),
    url(r'^by_tag/$', films_by_tag, name='films-by-tag-search'),

)

screening/models.py
import hashlib
import datetime
import random
import pytz
from django.db import models
from django.db.models import Q, Count
from django.contrib.auth.models import User
from copy import deepcopy
from pytz import timezone

from common.models import Country
from film.models import Film
from notifications.models import NewsItem, NewsItemType


class ActiveVenuesManager(models.Manager):
    def get_query_set(self):
        return super(ActiveVenuesManager, self).get_query_set().filter(deleted=False)


class Venue(models.Model):
    TIMEZONES = map(lambda tz: (tz, tz.replace('_', ' ')), pytz.common_timezones)

    name = models.CharField(max_length=250)
    # street_address = models.CharField(max_length=250, null=True, blank=True)
    city = models.CharField(max_length=250, null=True, blank=True)
    county = models.CharField(max_length=250, null=True, blank=True)
    state = models.CharField(max_length=250, null=True, blank=True)
    country = models.ForeignKey(Country)
    timezone = models.CharField(max_length=100, choices=TIMEZONES)
    phone_number = models.TextField(max_length=30, null=True, blank=True)
    # email = models.TextField(max_length=250, null=True, blank=True)
    # google_or_yelp = models.URLField(max_length=250, null=True, blank=True)
    website = models.URLField(max_length=250, null=True, blank=True)
    description = models.TextField()
    deleted = models.BooleanField(default=False)
    # profile_image = models.ImageField(upload_to='venues/profile_images', null=True, blank=True)
    #is_verified = models.BooleanField(default=False)
    user = models.ForeignKey(User, related_name='venues')

    objects = models.Manager()
    active = ActiveVenuesManager()

    def __unicode__(self):
        return self.name

    def model_class(self):
        return 'Venue'

    def belongs_to(self, user):
        return True if self.user == user else False

    @property
    def metadesc(self):
        return ','.join([self.name, self.street_address, self.city, self.country.name, self.description])

    @staticmethod
    def by_user(user):
        return Venue.active.filter(user=user)

    def url_service(self):
        if self.google_or_yelp.startswith('http://www.google.com'):
            return 'GOOGLE'
        elif self.google_or_yelp.startswith('http://www.yelp.com'):
            return 'YELP'
        return 'REVIEW'

    @staticmethod
    def get_with_film_count(min_length, max_length, min_year, max_year, country_id):
        if country_id != 'all':
            venues = Venue.active.filter(
                screenings__cancelled=False,
                screenings__decision='APPROVED',
                films__film__runtime__range=(min_length, max_length),
                films__film__year__range=(min_year, max_year),
                films__film__is_public=True,
                films__film__deleted=False,
                films__film__countries__pk=country_id
            )
        else:
            venues = Venue.active.filter(
                screenings__cancelled=False,
                screenings__decision='APPROVED',
                films__film__runtime__range=(min_length, max_length),
                films__film__year__range=(min_year, max_year),
                films__film__is_public=True,
                films__film__deleted=False
            )

        return venues.annotate(screening_count=Count('screenings')).annotate(film_count=Count('screenings__film', distinct=True))

    def get_random_film(self):
        return random.choice(self.films.all()).film if self.films.count() else None

    @property
    def public_screenings(self):
        return [s for s in self.screenings.all() if s.is_published and s.film.is_public]

    def has_in_progress_screening_of(self, film):
        for screening in self.screenings.all():
            if screening.is_accepted and screening.film == film and not screening.is_published:
                return True

        return False

    @staticmethod
    def have_shown(film_id):
        """
        Returns all venues that have a published screening for given film.
        """
        film = Film.active.get(pk=film_id)
        screenings = Screening.objects.filter(film=film)
        screenings = [s for s in screenings if s.is_published]
        return [s.venue for s in screenings]


class FilmOnVenue(models.Model):
    VENUE_START_YEAR = 1932
    VENUE_END_YEAR = 2015
    VENUE_YEARS = zip(
        range(VENUE_START_YEAR, VENUE_END_YEAR + 1),
        range(VENUE_START_YEAR, VENUE_END_YEAR + 1)
    )

    section = models.CharField(max_length=200, null=True, blank=True)
    awards = models.CharField(max_length=200, null=True, blank=True)
    venue = models.ForeignKey(Venue, related_name='films')
    year = models.PositiveIntegerField(choices=VENUE_YEARS, null=True, blank=True)
    film = models.ForeignKey(Film, related_name='venues')

    def __unicode__(self):
        return self.film.title + ' on ' + self.venue.name


class ProfitShare(models.Model):
    TYPES = (
        ('NOPROFIT', 'No profit'),
        ('SHARE', 'Share'),
        ('UPFRONT', 'Up front')
    )
    # These two are percentages, used when type == 'SHARE'
    film_share = models.IntegerField(null=True, blank=True)
    smplmchn_share = models.IntegerField(null=True, blank=True)

    # These two are exact amounts, used when type == 'UPFRONT'
    film_upfront = models.DecimalField(null=True, blank=True, max_digits=12, decimal_places=2)
    smplmchn_upfront = models.DecimalField(null=True, blank=True, max_digits=12, decimal_places=2)
    type = models.CharField(max_length=20, choices=TYPES)

    def __unicode__(self):
        return self.type

    @property
    def venue_share(self):
        if self.film_share and self.smplmchn_share:
            return 100 - self.film_share - self.smplmchn_share
        return None

    @property
    def venue_upfront(self):
        if self.film_upfront and self.smplmchn_upfront:
            return self.film_upfront + self.smplmchn_upfront
        return None


class ScreeningReport(models.Model):
    description = models.TextField()
    total_revenue = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return 'Yes ($' + str(self.total_revenue) + ')' if self.total_revenue else 'Yes'


class ScreeningReportFilmOwner(models.Model):
    PAID_PROMPTLY = (
        ('YES', 'Yes'),
        ('KINDA', 'Kinda'),
        ('NO', 'No')
    )
    RECOMMEND_VENUE = (
        ('YES', 'Yes'),
        ('EH', 'Eh'),
        ('NO', 'No')
    )
    REPORT_FRAUD = (
        ('YES', 'Yes'),
        ('NO', 'No')
    )

    description = models.TextField()
    paid_promptly = models.CharField(max_length=20, choices=PAID_PROMPTLY, blank=True, null=True)
    recommend_venue = models.CharField(max_length=20, choices=RECOMMEND_VENUE)
    report_fraud = models.CharField(max_length=20, choices=REPORT_FRAUD)


class Screening(models.Model):
    DECISIONS = (
        ('APPROVED', 'Approved'),
        ('DECLINED', 'Declined')
    )

    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    venue = models.ForeignKey(Venue, related_name='screenings')
    film = models.ForeignKey(Film, related_name='screenings')
    decision = models.CharField(max_length=20, choices=DECISIONS, null=True, blank=True)
    profit = models.OneToOneField(ProfitShare, related_name='screening', null=True, blank=True)
    cancelled = models.BooleanField(default=False)
    report = models.OneToOneField(ScreeningReport, null=True, blank=True)
    film_report = models.OneToOneField(ScreeningReportFilmOwner, null=True, blank=True)
    paid = models.BooleanField(default=False)

    def __unicode__(self):
        return self.film.title + ' @ ' + self.venue.name + '(' + str(self.id) + ')'

    @staticmethod
    def all_published():
        screenings = Screening.objects.filter(cancelled=False).all()
        return [s for s in screenings if s.is_published]

    @staticmethod
    def all_valid():
        screenings = Screening.objects.filter(cancelled=False).all()
        return [s for s in screenings if s.is_accepted]

    @staticmethod
    def for_user(user):
        return Screening.objects.filter(
            (Q(venue__user = user) | Q(film__user = user)) & Q(cancelled = False)
        ).prefetch_related('schedule')

    @property
    def title(self):
        return self.film.title + " @ " + self.venue.name

    @property
    def decision_made(self):
        return True if self.decision else False

    def approve(self):
        self.decision = 'APPROVED'

    def decline(self):
        self.decision = 'DECLINED'

    @property
    def is_accepted(self):
        return self.decision == 'APPROVED'

    @property
    def is_declined(self):
        return self.decision == 'DECLINED'

    @property
    def is_updated(self):
        film_owner_message = NewsItem.get_for_user(
            self.film.user,
            NewsItemType.SCREENING_UPDATED,
            object=self
        )
        return True if film_owner_message else False

    def cancel(self):
        self.cancelled = True

    def add_screening_at(self, t):
        if not self.schedule.filter(time=t).exists():
            self.schedule.add(ScreeningEvent(screening=self, time=t))

    @property
    def film_owners_earning(self):
        if self.profit.type == 'UPFRONT':
            return float(self.profit.film_upfront)
        elif self.profit.type == 'SHARE':
            if not self.report or not self.report.total_revenue:
                return None
            return float(self.report.total_revenue * (float(self.profit.film_share)/100))

    @property
    def simplemachine_earning(self):
        if self.profit.type == 'UPFRONT':
            return float(self.profit.smplmchn_upfront)
        elif self.profit.type == 'SHARE':
            if not self.report or not self.report.total_revenue:
                return None
            return float(self.report.total_revenue * (float(self.profit.smplmchn_share)/100))

film/templates/partials/_anon-msg.html
    <p class="menu-text"> Get in touch with the owner of <span>{{ film.title|upper }}</span>?</p>
    <p class="anon-login"><a href="{% url "login" %}?next={% url "film-details" film.id %}">LOG IN</a> or <a href="{% url "register" %}">REGISTER</a> to send {{ film.user.get_profile.name }} a message.</p>  

film/templates/partials/_curate_on_film_details.html
{% if user.is_authenticated %}
    {% if user.get_profile.active_curations %}
        <p class="menu-text"> Add this film to one of your lists: </p>
    {% else %}
        <p class="menu-text"> You have not yet created a list! Add this film to a new list in order to remember it. You can make your list public or private, depending on how secretive you are. </p>
    {% endif %}
    <div class="curations">
        {% for curation in user.get_profile.active_curations %}
            {% if film not in curation.films.all %}
                <p class="add-to-curation"><a href="/curations/{{ curation.id }}/film/{{ film.id }}/add/">{{ curation.title|upper }}</a></p>
            {% endif %}
        {% endfor %}
        <p class="create-new-curation"><a href="/curations/add/with_film/{{ film.id }}/">CREATE NEW LIST</a></p>
    </div>
{% else %}

<p class="menu-text"> Add <span>{{ film.title|upper }}</span> to one of your lists? Make lists to organize the films you want to remember.</p>
<p class="anon-login"><a href="{% url "login" %}?next={% url "film-details" film.id %}">LOG IN</a> or <a href="{% url "register" %}">REGISTER</a> to add this film to a list.</p>

{% endif %}

film/templates/partials/_exhibit.html
 {% if user.is_authenticated %}
    <p class="menu-text">Want to show this movie at your venue?</p>
    <p class="create-new-screening"><a href="{% url "add-screening" %}?for_film={{ film.id }}">CREATE NEW SCREENING</a></p>

{% else %}
    <p class="menu-text"> Book <span>{{ film.title|upper }}</span> to play at your festival or event?</p>
    <p class="anon-login"><a href="{% url "login" %}?next={% url "film-details" film.id %}">LOG IN</a> or <a href="{% url "register" %}">REGISTER</a> to create a venue called <span>{{ anonymous_curation_title }}</span> and book this film.</p>  

{% endif %}

film/templates/partials/_exhibition_file_download.html
{% if user.is_authenticated %}
    {% if can_download %}
        {% if film.exhibition_file and film.exhibition_file.uploaded %}
            <div class="exhibition-file-download">
            <a href="{% url "download-exhibition-file" film.id %}">HTTP</a>
            <a id="ftp-download-video" href="#">FTP</a>
            {% if request.user.get_profile.dropbox_access_token %}
            <a id="dropbox-download-video" href="#">DROPBOX</a>
            {% else %}
            <p class="menu-text">If you would like to download the file to your Dropbox:<br /></p> <a href="#" id="link-with-dropbox-btn">LINK YOUR DROPBOX</a>
            {% endif %}
            </div>
        {% else %}
            <p class="menu-text">UhOh! We don't actually seem to have an exhibition file for this film. Once {{ film.user.get_profile.name }} uploads a file, you will be able to download it here! </p>
        {% endif %}
    {% else %}
        {% if download_request %}
            {% if not download_request.decision_made %}
                <p class="menu-text">You will be notified when {{ film.user.get_profile.name }} responds to your request</p>
            {% elif download_request.is_declined %}
                <p class="menu-text">Your request to download this film has been declined.</p>
            {% endif %}
        {% else %}
            {% if film.exhibition_file and film.exhibition_file.uploaded %}
                <div class="download-no-permission">
                    <p class="menu-text">Screening {{ film.title|upper }} at your event? Download an exhibition-quality quicktime file! Send a request and, if it is accepted, you will be able to download the file here. </p>
                    <button type="button" id="send-download-request">SEND DOWNLOAD REQUEST</button>
                </div>
            {% else %}
                <p class="menu-text">{{ film.user.get_profile.name }} hasn't uploaded an exhibition file for this film yet. Once they do, you will be able to send a request to download the high-quality quicktime file for exhibition purposes.</p>
            {% endif %}
        {% endif %}
    {% endif %}
{% else %}
    
    <p class="menu-text"> Playing <span>{{ film.title|upper }}</span> at an exhibition? Here you will be able to request permission to download a high-quality quicktime file to screen at your event. </p>
    <p class="anon-login"><a href="{% url "login" %}?next={% url "film-details" film.id %}">LOG IN</a> or <a href="{% url "register" %}">REGISTER</a> to send a download request.</p>  
    
{% endif %}
    

<script type="text/javascript">
    $(window).ready(function(){
        $("a#ftp-download-video").on("click", function(){
            $.get("{% url "download-exhibition-file-ftp" film.id %}", function(data){
                $('#exhibition-file-container').html(data);
            });
        })

        $("a#dropbox-download-video").on("click", function(e) {
            $.get("{% url "download-exhibition-file-dropbox" film.id %}", function(data){
                $('#exhibition-file-container').html("<p>" + data.msg + "</p>");
            });
        });
    });
</script>

film/templates/partials/_exhibition_file_upload_dropbox_files.html
{% for f in dropbox_files %}
<button id="{{ f.path }}">
<span class="path">{{ f.path }}</span>
<span class="size">{{ f.size }}</span>
<span class="modified">{{ f.modified }}</span>
</button>
{% empty %}
    You have no films in your smplmchn folder on Dropbox.
{% endfor %}

film/templates/partials/_film_details_module.html
{% load staticfiles %}
{% load common_tags %}

<script type="text/javascript">
    $(window).ready(function(){
        $('img.play-button').on('click', function(e){
            var film_id = $(e.currentTarget).parents('div.play-trailer').attr('data-id');
            $.get('/films/' + film_id + '/trailer/', function(data){
                $(e.currentTarget).parents('div.play-trailer').siblings('div.embedded-player').html(data);
            $(e.currentTarget).parents('div.play-trailer').hide();
            });
            mixpanel.track("trailer viewed", {
                "film_id": film_id
            });
        });

        $("a.toggle-curate-container").on('click', function(e){
            e.preventDefault();
            var container_class = $(e.currentTarget).attr('data-class');
            $("div." + container_class).toggle();
            $(e.currentTarget).parents('div.add').toggleClass('active');
            return false;
        })

        $("button#close-submenu").on('click', function(e){
            e.preventDefault();
            $(e.currentTarget).parents('div.film-curate-container').hide();
            $(e.currentTarget).parents('div.add').removeClass('active');
            return false;
        })
    });
</script>

{% with results=films %}
    {% include 'helpers/pagination.html' %}
{% endwith %}

{% for film in films %}
    <div class="film-module">
        <div class="container">
            <div class="trailer">
                {% if film.trailer_embed_code %}
                    <div class="play-trailer" style="background-image: url('{{ film.thumbnail_link }}')" data-id="{{ film.id }}">
                        <img src='{% static "play_btn.png" %}' class="play-button">
                    </div>
                    <div class="embedded-player"></div>
                {% else %}
                    <div class="play-trailer">
                        <div class="has-no-trailer">
                        <p>This film has no trailer.</p>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="not-trailer">
                <div class="result-title">
                    <h3><a href="{% url "film-details" film.id %}">{{ film.title|upper }}</a></h3>
                    <p class="info"><span>{{ film.director|upper }}</span><span>{% for c in film.countries.all %}{{ c }}{% if not forloop.last %} + {% endif %}{% endfor %}</span><span>{{ film.year }}</span><span>{{ film.runtime }}min</span></p>
                    {% comment %}
                    <!--
                    <p class="tags">
                    {% for tag in film.tags.all %}
                        <a href="{% url "films-by-tag" tag %}">{{ tag }}</a>
                    {% endfor %}
                    </p>
                    -->
                    {% endcomment %}
                </div>
                <div class="add">
                    <nav>
                        <a href="{% url "film-details" film.id %}" class="learn-more">LEARN MORE</a>
                        <a href="#" data-class="curate-container-{{ film.id }}" class="toggle-curate-container">ADD</a>
                    </nav>
                    <div class="film-curate-container curate-container-{{ film.id }}">
                        {% include "partials/_curate_on_film_details.html" %}
                        <button type="button" id="close-submenu">CLOSE</button>
                    </div>
                </div>
                <div class="text">
                {% if reviewer_id %}
                    {% with reviews=film|sort_film_reviewer:reviewer_id %}
                        {% include "partials/_film_reviews_module.html" %}
                    {% endwith %}
                {% elif organization_id %}
                    {% with reviews=film|sort_film_organization:organization_id %}
                        {% include "partials/_film_reviews_module.html" %}
                    {% endwith %}
                {% else %}
                    {% with reviews=film.reviews.all %}
                        {% include "partials/_film_reviews_module.html" %}
                    {% endwith %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <p>No films in our database have been shown on this festival</p>
{% endfor %}

{% with results=films %}
    {% include 'helpers/pagination.html' %}
{% endwith %}

film/templates/partials/_film_menu.html
{% if film.deleted %}
    <div>
        <p class="inactive">INACTIVE</p>
    </div>
{% elif film.user == user %}
    <div>
        {% if not film.is_public %}
        <a href="{% url "add-film-logistics" film.id %}">(UNLISTED)</a>
        {% endif %}
        <a href="#preview-file" class="menu-link">PREVIEW FILE</a>
        <a href="#exhibition-file-container" class="menu-link">EXHIBITION FILE</a>
        <a href="{% url "edit-film" film.id %}">EDIT FILM INFO</a>
        <a href="#curate-container" class="menu-link" id="profile-menu-add">ADD</a>
    </div>
{% else %}
    <div>
        <a href="#exhibition-file-container" id="exhibit-link" class="menu-link">QT FILE</a>
        <a href="#prev-file-box" id="preview-link" class="menu-link">WATCH</a>
        <!--<a href="#pay-container" id="pay-link" class="menu-link">PAY</a>-->
        <!--<a href="#exhibit" id="exhibit-link" class="menu-link">BOOK</a>-->
        {% if user.is_authenticated %}
        <a href="{% url "view-or-start-conversation" film.user.id %}" class="contact menu-link">MESSAGE</a>
        {% else %}
        <a href="#anon-msg" id="anon-msg-link" class="menu-link">MESSAGE</a>
        {% endif %}
        <!--<a href="#review-box" id="review-box-link" class="menu-link">REVIEW</a>-->
        <a href="#curate-container" class="menu-link" id="profile-menu-add">ADD</a>
    </div>
{% endif %}

film/templates/partials/_film_overview.html
<div style="border: 1px dotted gray; margin-bottom: 50px; height: 10em; padding: 5px">
    <div class="span3" style="padding-top: 30px">
        <a href="{% url "film-details" film.id %}{{ film.title|slugify }}" style="font-size: 2em;">{{ film.title|upper }}</a>
    </div>
    <div class="span8">
        <img src="/media/{{ film.profile_image }}" style="width: 100%; height: 9em"/>
    </div>
</div>

film/templates/partials/_ftp_file_upload.html
{% if error %}
<p>{{ error }}</p>
{% else %}
<p class="menu-text">Here are credentials for your file {% if download %}download{% else %}upload{% endif %}.</p>
<br />
<p>
Server: {{ server }}
<br />
Username: {{ username }}
<br />
Password: {{ password }}
<br />
Port: 21 (default)
</p>
{% endif %}

film/templates/partials/_media.html
{% load fb_versions %}

{% with film.images.all as images %}
{% with film.videos.all as videos %}
{% if images or videos %}
<hr>
<h4>Media</h4>
	{% if images %}	
	<div class="row">
		{% for item in images %}
		<div class="span2">
			<img src="#" id="image-item-{{item.id}}" class="media-item" />
			<p>
				<span class="label pull-left media-item-label">{{item.get_type_display}}</span>
				{% if is_admin %}&nbsp;<a href="{% url "film_image_delete" item.id %}"><span class="label label-important pull-right">X</span></a>{% endif %}
			</p>
			
			{% if item.description %}
			<script>
				$(window).ready(function(){
					$('#image-item-{{item.id}}').popover({
						'title': '{{item.get_type_display}}',
						'content': '{{item.description|linebreaksbr}}',
						'placement': 'top',
						'trigger': 'hover'
					});
				});
			</script>
			{% endif %}
		</div>
		{% endfor %}
	</div>
	{% endif %}

	{% if videos %}
	<div class="row">
		{% for item in videos %}
		<div class="span2">
			<iframe width="170" height="96" src="{{ item.get_video_url }}" frameborder="0" class="media-item" allowfullscreen></iframe>
			<p>
				<span id="video-item-{{item.id}}" class="label pull-left media-item-label">{{item.get_type_display}}</span>
				{% if is_admin %}&nbsp;<a href="{% url "film_video_delete" item.id %}"><span class="label label-important pull-right">X</span></a>{% endif %}
			</p>
			{% if item.description %}
			<script>
				$(window).ready(function(){
					$('#video-item-{{item.id}}').popover({
						'title': '{{item.get_type_display}}',
						'content': '{{item.description|linebreaksbr}}',
						'placement': 'top',
						'trigger': 'hover'
					});
				});
			</script>
			{% endif %}
		</div>
		{% endfor %}
	</div>
	{% endif %}
{% endif %}
{% endwith %}
{% endwith %}